server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5t6u9Q1DBFwYQkRVm4Fc
    keySecret: h5hb220jYEQNGsU9dE70Yohxmsw3mr
    bucketName: finance-file-bigdragon